### ISSUE TITLE
Compiling on AIX

### ISSUE THREAD

**Issue by glewis64** [muquit/mailsend#139]
I'm attempting to compile mailsend on AIX with cc compiler.  The ./configure successfully completes, but when I "make", it immediately returns:
$ make                                                                         
        make -C libs/libmutils                                                 
make: Not a recognized flag: C                                                 
usage: make [-einqrst] [-k|-S] [-d[A|adg[1|2]mstv]] [-D variable] [-f makefile]
[-j [jobs]] [variable=value ...] [target ...]                                  
make: 1254-004 The error code from the last command is 2.                      
                                                                               
                                                                               
Stop.                                                                          

I did a little digging and I see in the Makefile there is +make -C libs/libmutils.  The linux (Red Hat) man page for make says this changes directories before continuing.  The AIX make command doesn't have this switch.

What do I need to do to proceed?

**Comment by muquit** [comment]
Please change the following lines in ```Makefile.in``` and run ```configure```.  I will update the Makefile.in in trunk.

```
libmsock: libmutils
    +make -C libs/libmsock

libmutils:
    +make -C libs/libmutils

libsll:
    +make -C libs/libsll
```
To
```
libmsock: libmutils
    (cd libs/libmsock && make)

libmutils:
    (cd libs/libmutils &&  make)

libsll:
    (cd libs/libsll && make)
```

**Comment by glewis64** [comment]
Thank you for your super quick and successful answer!!!!
