### ISSUE TITLE
AIX Switching attachment extensions to lowercase

### ISSUE THREAD

**Issue by glewis64** [muquit/mailsend#140]
I have built mailsend for RHEL 6.4 and have successfully tested it using both lowercase PDF file attachments and uppercase PDF file attachments.  I then moved onto AIX and have successfully built on this platform.  In my testing on AIX, the attachments are always looking for a lowercase .pdf extension even though on the command line I specified the file with an uppercase .PDF extension.  

How do I overcome this AIX only issue?

Thanks in advance!

**Comment by glewis64** [comment]
AIX is correctly maintain the case of the specified filename, but it is always changing the extension to lowercase no matter what case was specified on the command line.

**Comment by muquit** [comment]
mailsend does not manipulate filenames. For whatever reason, file was passed to mailsend as lower case. You can put some debug messages in smtp.c around line# 707 and see what is going on, something like...

```(void) fprintf(stderr,"file: %s\n",a->file_path);```

**Comment by glewis64** [comment]
Here's what I'm posting on the command line and what I'm receiving back:

$ a" -attach MiXeD.pDf,application/PDF,a                                     <  
Error: smtp.c (711) - Could not open file for MiXeD.pdf reading (No such file o)
Error: smtp.c (779) - Could not encode attachment MiXeD.pdf                     
Error: smtp.c (894) - failed to send attachment MiXeD.pdf                       

Isn't the error message providing me the same information as the debug message?

The file on disk is named MiXeDpDf.pDf

**Comment by muquit** [comment]
In main.c, please add a line after line#288 to check how the file was passed, e.g.
```
attach_file=argv[i];
(void) fprintf(stderr,"+++++++++++ attach: '%s'\n",attach_file);
add_attachment_to_list(attach_file);
```

For easy troubleshooting, Instead of specifying comma separated, please do this:
```
-mime-type 'application/pdf' -disposition 'attachment' -attach '/full/path/of/MixeD.pDF'
```
Also do:
```
/bin/ls -lt '/full/path/of/MixeD.pDF'
```

**Comment by glewis64** [comment]
When I was receiving this error we were beginning to get some smtp errors.  We have resolved those errors this morning and now it is no longer messing with the extension of the pdf attachment.

I'll chalk this one off as weird as it is working now.  I didn't get to the point of putting in the debug code.

Thanks for your help.

**Comment by muquit** [comment]
I am not convinced that ```mailsend``` is doing it, because there is no such code in it to do such thing, unless there is some kind of bug triggering it. You can put the debug messages in various locations as I suggested earlier to find out when the extension is changing (from input to while it opens the file).
Thanks

**Comment by muquit** [comment]
I can not seem to reproduce it. But it is possible there is bug in parsing the -attach line. Instead of comma separated, would try like following?

```
-mime-type 'application/pdf' -disposition 'attach' -attach 'SA330P_20120816103135.PDF'
```

Thanks.

**Comment by glewis64** [comment]
Ran as requested … same result.

$ type 'application/pdf' -disposition 'attachment' -attach 'SA330P_2012081610*
+++++++++++ attach: 'SA330P_20120816103135.PDF'
file: SA330P_20120816103135.pdf
Error: smtp.c (712) - Could not open file for SA330P_20120816103135.pdf reading)
Error: smtp.c (780) - Could not encode attachment SA330P_20120816103135.pdf
Error: smtp.c (895) - failed to send attachment SA330P_20120816103135.pdf

Could not send mail

I’m trying to follow the code to see where to place more debug code.

Thanks so much for your help.
Gayle

**Comment by muquit** [comment]
ok I was able to reproduce it, I will try to fix it over the weekend.

**Comment by glewis64** [comment]
I was just getting ready to send you an email.  I debugged it down to the get_mime_type routine in utils.c

If the application found the attachment is a binary, this routine got called and when it lowered the case of the extension it actually lowered the case of the file_path sent into the routine as well.

I was able to reproduce it on my compile server as well.  The PDF I was using on my compile server, it didn’t think it was a binary file so it never called get_mime_type.

Is this what you’re seeing as well?

Thanks so much for your help.
Gayle

**Comment by muquit** [comment]
Yes it was the root cause. Instead of allocating memory before determining extension and lower casing it, it was modifying the passed string, which was the path of the attachment. Good find!
Thanks

**Comment by glewis64** [comment]
Good morning,

Any luck in getting this fixed?

Thanks,
Gayle

**Comment by muquit** [comment]
Please try the trunk.
Thanks.
