### ISSUE TITLE
how to compile mailsend-1.19 in raspberry pi 3b+

### ISSUE THREAD

**Issue by ck932** [muquit/mailsend#146]

**Comment by ck932** [comment]
I compile mailsend-1.19 in raspberry pi 3b+ ，but there is something wrong during compiling:

/usr/include/openssl/hmac.h:28:1: note: declared here
 DEPRECATEDIN_1_1_0(__owur int HMAC_Init(HMAC_CTX *ctx, const void *key, int len,
 ^
utils.c:795:9: warning: unused variable ‘ctx’ [-Wunused-variable]
         ctx;
         ^~~
Makefile:56: recipe for target 'utils.o' failed
make: *** [utils.o] Error 1

Counld you tell me how to fix it , thanks :-)

**Comment by muquit** [comment]
Please try the code from trunk. It compiles fine on pi 3b+ with OpenSSL

```
pi@raspberrypi:~ $ apt-cache policy openssl
openssl:
  Installed: 1.1.0f-3+deb9u2
  Candidate: 1.1.0f-3+deb9u2
  Version table:
 *** 1.1.0f-3+deb9u2 500
        500 http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages
        100 /var/lib/dpkg/status

pi@raspberrypi:~ $ mailsend -V
mailsend Version: @(#) mailsend v1.20b2
Compiled with OpenSSL: OpenSSL 1.1.0f  25 May 2017
```
