### ISSUE TITLE
OpenSSL 1.1.1a

### ISSUE THREAD

**Issue by SirDan1963** [muquit/mailsend#147]
Hello,

We are using buildroot to cross compile for ARM. Linux kernel 4.14 and OpenSSL 1.1.1a.

We get the errors below when compiling.

utils.c: In function ‘encode_cram_md5’:
utils.c:795:9: error: storage size of ‘ctx’ isn’t known
         ctx;
         ^~~
utils.c:835:5: warning: implicit declaration of function ‘HMAC_CTX_init’; did you mean ‘HMAC_CTX_new’? [-Wimplicit-function-declaration]
     HMAC_CTX_init(&ctx);
     ^~~~~~~~~~~~~
     HMAC_CTX_new
utils.c:836:5: warning: ‘HMAC_Init’ is deprecated [-Wdeprecated-declarations]
     HMAC_Init(&ctx,secret,strlen(secret),md5);

Any chance for a patch to fix this?

Thank you,
Dan

**Comment by muquit** [comment]
Please clone the code from master branch, it will work.
Thanks.

**Comment by SirDan1963** [comment]
Thank you, it works!

[root@RMS-300v2: /root# mailsend -V
mailsend Version: @(#) mailsend v1.19
Compiled with OpenSSL: OpenSSL 1.1.1a  20 Nov 2018
