### ISSUE TITLE
How to send a mail to undisclosed recipients

### ISSUE THREAD

**Issue by jlselles** [muquit/mailsend#86]
Hello. I'm trying to send a mail to several directions by I don't want to declare anyone of them.
If I don´t put the "-to" clausule with data , mailsend don´t work.
I'm putting all the destination emails in then "-bc" clause .

Thanks.

**Comment by muquit** [comment]
You've to put at least one -to address and the addresses you don't want to disclose, specify them as comma separated strings with -bc. 
Example: ```-to "jdoe@example.com" -bc "foo@example.com,bar@example.com"```

SMTP server will not disclose the addresses specified with -bc (Blind Carbon Copy).

Thanks.

**Comment by jlselles** [comment]
Thanks. That's what I'm doing but I don´t want to declare neither the -to address.

**Comment by muquit** [comment]
Did you try the ```-list-address list.txt``` option? Add the addresses one address per line in the file list.txt. If your list is not huge, it should work.

Thanks.
