### ISSUE TITLE
Problem with the address xxx.yyy@gmail.com

### ISSUE THREAD

**Issue by BajaPL** [muquit/mailsend#90]
I have called the address xxx.yyy@gmail.com - unfortunately can not be sent through mailesend.exe. I checked with a standard login www@gmail.com - works without a problem.

**Comment by muquit** [comment]
Please give an example. mailsend does not interpret from, to or address used in SMTP authentication, it is up to the SMTP server to do so.
Thanks.

**Comment by BajaPL** [comment]
1. good  - subiekranczo@gmail.com
2. wrong - ranczo.tea@gmail.com 
In both cases, the configuration is the same. In addition to the email address and password - of course.
